### ISSUE TITLE
1.8.3 - Camping Tent - Failed to complete build, but did

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#234] opened 2014-10-14 19:16 UTC
I placed a camo net then tried to place camping tent under it, at first my option changed to “cancel build” so I middle mouse clicked and got the “failed to build camping tent” and the tent was not placed but still in my inventory.
I placed a camping tent under the net again but walked it to the edge of net, still got the “cancel build” so I click again and got “failed to build camping tent” but a tent was built, and I still had one in my inventory.
If I place tent under net and move beyond edge of net, it places normally.
The tents that failed to build I can add items, but am not the owner of them.
![2014-10-14_00003](https://cloud.githubusercontent.com/assets/8584071/4635124/8dafeb8a-53d6-11e4-877e-99f2e22407ae.jpg)

**Comment by KPanicEKS** [comment] 2014-10-15 08:51
why is the "wontfix" tag marked on this report? If not addressed I can see tent cities popping up all over the place like the early days when duping tents were very easy.

**Comment by R4Z0R49** [comment] 2014-10-15 16:18
We have to go over a review system before the files get released and the files are already in BIS hands. So before the next dev push to steam we wont it to be fixed hence the tag.

We will no longer be releasing the files like we use to we will have a dev branch on steam we push to that then over to a stable branch once its all working as it should be.

**Comment by Detoeni** [comment] 2014-10-15 20:34
iffy tents looked to have been removed by clean up or new build (watermarked 1.8.3)

**Comment by facoptere** [comment] 2014-10-25 16:27
Tents have not been removed, they never existed. Maybe it's the "ghost" version of the tents that were not removed from screen, anyway these tents are not saved to the hive.
I can't reproduce this glitch.
Players can pitch a tent under a camo_net, which is not considered as a building now.

**Closed as completed by facoptere** 2014-10-25 16:27 UTC
Labels: type:bug, status:fixed, DevelopmentBuild
