### ISSUE TITLE
Vehicles, stashes, and tents missing after restart

### ISSUE THREAD

**Issue by AggrOnline** [DayZMod/DayZ#503] opened 2015-06-09 15:51 UTC
I have had to restart my server on three occasions since going live (three days) my admin regularly checks on the server after restarts and he reported missing vehicles and stashes so it looks like on three occupations the game was not able to read data from objects_data however it was able to get character data as players would show in the correct position with all their gear.

I have DayZadmin running could this be the problem?

**Comment by ghost** [comment] 2015-06-09 15:54
It´s maybe the "startup sequence aborted"-bug. When the first player connecting to a server aborts the login process, the stream of items from the database to the server instance may get corrupted and the items (tents, stashes, vehicles, buildables) do not spawn to the server. 

When you restart the server, all stuff should be there. Make sure to crosscheck your items in the database. If they are still in there, it´s the described bug.

**Comment by AggrOnline** [comment] 2015-06-09 15:54
when i checked in MyPhp admin and expanded object_data,  i see a warning as follows:

Notice in ./libraries/tbl_columns_definition_form.inc.php#55
 Undefined variable: server

Backtrace

./libraries/structure.lib.php#2447: include(./libraries/tbl_columns_definition_form.inc.php)
./tbl_structure.php#45: PMA_displayHtmlForColumnChange(
string 'myUsername',
string 'object_data',
NULL,
string 'tbl_structure.php',
)

any ideas what this is?

**Comment by ghost** [comment] 2015-06-09 15:55
Seems to be a phpmyadmin issue.

**Comment by AggrOnline** [comment] 2015-06-09 15:56
the error is on every field name I click on in object_data table

**Comment by ghost** [comment] 2015-06-09 16:00
Have you tried any other method? e.g. Navicat? Just to figure out if it´s a phpmyadmin issue or a corrupted database?

**Comment by AggrOnline** [comment] 2015-06-09 16:12
Do you think that will work? its got to be table/data issue since the only thing that doesn't appear in the game is stuff from object_data although restarting the server brings everything back in the game! I will try another client and report back

**Comment by ghost** [comment] 2015-06-09 16:13
Restarting brings back all items? Then it´s likely be the bug I described in the first reply.

**Comment by AggrOnline** [comment] 2015-06-09 16:19
yes all come back after restart, what is the fix? it's happening almost every other restart! I dont think its related to first player aborting simply because there are no players until we get to the server after  restart!

**Comment by ghost** [comment] 2015-06-09 16:20
As far as I know, there is no fix for this. @R4Z0R49 , got any suggestions?

**Comment by R4Z0R49** [comment] 2015-06-09 16:48
No idea it yet this is the first report of it happening every restart.

**Comment by ghost** [comment] 2015-06-09 17:06
I derive from his postings that this is not happening on every single restart. So I guess it´s the known bug.

**Comment by R4Z0R49** [comment] 2015-06-09 17:07
We are looking into it

**Comment by AggrOnline** [comment] 2015-06-09 17:50
Thank you guys I will wait patiently ! 

It's not every restart but every other almost!

**Comment by vinyljunkie** [comment] 2015-06-10 07:37
Hey guys, Isn't this what happens if a client joins the server too soon after a restart and disconnects/crashes? 
A solution is to lock the server after restart until it has started up then unlock to let players in to the lobby.

**Comment by ghost** [comment] 2015-06-10 07:54
This is the way I can reliably reproduce this:
- Restart the server.
- Connect as first player.
- Wait until the server starts to read items from the database.
- While reading and streaming to the server, disconnect the client.
- Boom. No items on map.

Maybe I´m wrong about this and there is another cause. But locking the server might not do the trick,  if the error is triggered as described.

**Comment by kichilron** [comment] 2015-06-10 09:21
That is exactly the issue described above. 

When a player joins and then crashes or aborts, the stream of objects is interrupted. This is an issue we were trying to battly for many patches now - but there's currently no solution for that.

**Comment by ghost** [comment] 2015-06-10 09:32
I´m not in any way competent to make a good suggestion... just making a stupid guess here. Maybe the spawning of items should be separated from a player joining. Server starts up in locked state, server gets all items... server goes idle, unlocks... players are free to connect. 

But I think this an issue of the Arma2OA Server, right?

**Comment by kichilron** [comment] 2015-06-10 09:35
Well, up until a player joins to kick off the process of the server starting up it's theoretically a vanilla ARMA 2 Server.

Only when a player joins, the mission is loaded and thus the DayZ Stuff being loaded in. That is the reason why the vehicles are being loaded when a player joins.

**Comment by ghost** [comment] 2015-06-10 09:37
Ah ok. Thanks for clarifying.

**Comment by R4Z0R49** [comment] 2016-08-07 01:35
This is an ongoing issues we are looking to resovle

**Closed as completed by R4Z0R49** 2016-08-07 01:35 UTC
Labels: type:bug, status:wantfix
