### ISSUE TITLE
ALT + F4 causing the dead players body to disappear

### ISSUE THREAD

**Issue by VidKo** [DayZMod/DayZ#418] opened 2015-04-30 17:30 UTC
There is a real problem in game:

A player gets killed and while he's on the death screen with the 5 second timer he can easily rage quit by pressing ALT + F4 which will cause his body to sink into the ground and disappear thus making it impossible for his killer to loot his body.

We started getting a lot of complaints lately on Europa server about bodies disappearing right after you kill someone. We even tested it on our 1.8.5 test server and confirmed it 100% every time. (when you have the 5 second timer to wait to return to lobby, just press ALT + F4)

If a fix is not possible, is it possible to somehow make it be readable in the logs?

**Comment by R4Z0R49** [comment] 2015-04-30 18:08
This isn't new Admins should be able to deal with this problem pretty easy but ill take a look see what we can do about it.

**Comment by vinyljunkie** [comment] 2015-04-30 19:05
Awesome, thanks!

**Comment by vinyljunkie** [comment] 2015-05-26 14:43
We've done some testing on this and dead players bodies do dissapear sometimes even though the dead player does not press alt+f4.

**Comment by R4Z0R49** [comment] 2015-05-26 18:24
yea its an old issue we will look into it on the next patch.

**Comment by ebayShopper** [comment] 2017-01-29 22:14
ed231fe

Duplicate of https://github.com/EpochModTeam/DayZ-Epoch/issues/1825

**Closed as completed by ebayShopper** 2017-01-29 22:14 UTC
