### ISSUE TITLE
Sandbag Packs

### ISSUE THREAD

**Issue by CoftSock** [DayZMod/DayZ#450] opened 2015-05-17 01:43 UTC
![View 1](http://s4.postimg.org/klgr2tm0d/sandbagpack1.png)
![View 2](http://s4.postimg.org/9offe1z8t/sandbagpack2.png)
![side](http://s4.postimg.org/s2pyi1bjh/sandbagpackside.png)

as a craftable backpack thoughts?

**Comment by R4Z0R49** [comment] 2015-05-17 09:36
Might be nice to update the backpack we already craft.

**Comment by R4Z0R49** [comment] 2015-05-17 12:34
This one 

https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/Configs/CfgCrafting/Recipes/Other/BackPack.hpp

**Comment by Jbird206** [comment] 2015-05-19 03:18
A fine idea. Frankly I'll find a good pack well before I discover four rags or what not.

**Comment by KPanicEKS** [comment] 2015-05-19 04:09
My suggestion is to remove the Alice pack from the loot tables (it's
insainly common right now) and turn it into the craftable bag. Also since
it doesn't have a zipper and rather a flap remove the zipper sounds so
people can use it as a quieter backpack option. There is a cloth sound I
just can't think of what it is atm. That way people that want to stay
stealthy would have to work on finding the parts to craft it.

Also since the British and Alice currently hold the same slots (18) I think
making the British hold 20 slots would be a reasonable change.

**Comment by HeroSmurf** [comment] 2015-05-19 04:13
Ugh as much as I have loved finding backpacks 3-4x faster; 
I have to agree. 

And I like R4Z0R's idea of upgrading existing recipes and if it became the Alice; that would be worth it. 

But then again I really like finding bigger backpacks. 
[Takes rags and bottle of liquid out of easily found big backpack]
[Chloroform's M0tzilla] shhhhhhhh. sleep now, no more posting good points.

**Comment by Jbird206** [comment] 2015-05-19 04:21
There's the journal opening sound? That's the only cloth type sound I can think of.

**Comment by CoftSock** [comment] 2015-05-19 10:07
agree that the alice pack is just everywhere, a orange house had 3 the other night. the reason i brought up the "sandbag backpack" was to find some in between with small and large packs depends on the sandbag i guess but they should be bigger than an alice pack

**Comment by KPanicEKS** [comment] 2015-05-19 10:14
I like the idea of a craftable sandbag too. I thknk it's a great idea. make
it hold as much as the patrol pack but also make it silent like the new
purposed alicepack.

1 sandbag = 1 string = sandbag pack = 8 slots

also let sandbags work like rags so we can craft an alicebag with say 5
sandbags and 3 string (or something like that)

also the sound that would work is when you access loot on the ground. it's
a soft fabric clothey sound. that would be perfect for opening and closing
the craftable non zipper bags.

**Comment by CoftSock** [comment] 2015-05-19 10:20
@M0tzilla the sound is https://github.com/DayZMod/DayZ/tree/Development/SQF/dayz_sfx/effects action_open_inventory_#.ogg 
what about rope instead of string?

**Comment by KPanicEKS** [comment] 2015-05-19 10:37
yeah good call, rope is harder to find.

I personally like action_open_inventory_2.ogg

**Comment by thcNox** [comment] 2015-05-20 03:44
You'd have to nerf existing packs considerably before I'd consider bothering with crafting this one. Existing packs are quite common except the czech/coyote and frankly this one isn't too flattering in the looks department imho :p

**Comment by CoftSock** [comment] 2015-05-20 04:54
slammed! but really the alice packs do need a nerf

**Comment by Lukethero** [comment] 2015-05-20 14:09
Agreed with @motzilla. Here is an idea for rebalance though. Switch the ACU pack and the Alice size. The ACU is much more rare due to it only spawning in super markets, why not make it have the better size? Also decrease the Alice spawn like everyone is suggesting.

What does everyone else think about switching the inventory size of those two though? I think it puts the bacpacks in their own little niche.

Edit: Changed Czech to ACU

**Comment by AsFoxy** [comment] 2015-05-20 14:15
It doesn't make sense when you look at the two. Rather swap their spawns. To be honest though i think the backpacks need an overall rebalance. Perhaps something like:

| Backpack | Size |
| --- | --- |
| Czech vestpouch | 8 |
| Patrol pack | 10 |
| Assault pack | 12 |
| New crafted backpack | 14 |
| Survival ACU | 16 |
| Alice    backpack | 18 |
| British assault pack | 20 |
| Czech backpack | 22 |
| Coyote backpack | 24 |

**Comment by Lukethero** [comment] 2015-05-20 14:21
Also if you want to add this backpack you will need to find someone to add the proxies to the skin, which is not as easy as it would appear.

**Comment by Lukethero** [comment] 2015-05-20 14:29
@asFoxy No you are right, what I meant to say is switch the survival ACU and the Alice. My bad, I was not thinking.  I agree with all the changes you said, except, as previously stated, switch Alice and ACU size.

**Comment by thcNox** [comment] 2015-05-20 17:55
@AsFoxy I'd switch Czech backpack with Coyote in your list

**Comment by R4Z0R49** [comment] 2015-05-20 18:11
Now add weapons into the mix you have only talked about magazines.

**Comment by AsFoxy** [comment] 2015-05-20 18:37
Why on earth Nox? It's already better camouflaged and then it would be better in every way. Rather have a tradeoff between the two.

EDIT: @Lukethero there is no need to add proxies to skins for a new backpack.

**Comment by KPanicEKS** [comment] 2015-05-20 19:02
The czech pack is visually the largest bag in the game so it would make
sense to have it carry the most. Plus it's camo so that should further make
the case that it's the best bag in the game. I also like the idea of
swapping the czech spawn chance with the coyote backpack as I find czechs *much
*more often than I find coyote backpacks

Czech vestpouch 8
Patrol pack 10
Assault pack 13
Survival ACU 16
Alice 18 < remove from loot tables and make this the craftable bag (5
sandbags + 2 rope)
British 20
Coyote backpack 22
Czech backpack 24

**Comment by kichilron** [comment] 2015-05-20 19:10
One thing to keep in mind:

A downgrade of sizes of a particular backpack isn't doable without either
- massive complaints by the community
- A lot of work to not have items vanish upon login after update

**Comment by thcNox** [comment] 2015-05-20 19:27
Simply because among the people I play with the Czech backpack is the most desirable and It would ruin the game for me a little bit if it didn't at least  match the coyote in capacity. If that makes it better that the Coyote on the whole you might balance the Czech by making it rarer than the Coyote. 

Basically Czech backpacks has been the holy grail of backpacks, if you can make them a bit rarer than today that would just make it better

**Comment by AsFoxy** [comment] 2015-05-20 19:32
It's the most desirable because it's arguably the best. If the British had 30 slots then it would be the most desirable, and the holy grail as you say, no?

**Comment by thcNox** [comment] 2015-05-20 19:42
To a degree, doesn't make as much sense as obviously since the Czech is great due to it's size/looks, camo and a competitive capacity. It doesn't rely solely on it's capacity which makes it the perfect candidate for being the most desirable backpack.

I've always like the relationship between Coyote and Czech in terms of "desirability" but currently the problem is that the Coyote is rarer than the Czech while it really should be the other way around. Perhaps make it so only Coyote's can spawn in Firestations instead of Czech for example.

**Comment by AsFoxy** [comment] 2015-05-20 19:56
The point i'm trying to make here though is that it's bad design to have a single best item in a category. Each item should have a tradeoff, in this case camouflage versus size. That's my opinion anyway.

**Comment by thcNox** [comment] 2015-05-20 20:30
I just don't think it makes sense to apply that logic to backpacks in this game when there's a fairly clear and linear progression in backpacks currently. The only oddity in my opinion right now is as I said that the Coyote shouldn't be rarer than the Czech. The way the Czech and Coyote share the same capacity right now is perfectly fine. The fact that the Czech has camo puts it on top but that imo is also fine. I would just like to see the spawn rate lowered and coyote made more common.

**Comment by Jbird206** [comment] 2015-05-20 22:31
Alright, lock down this thread already.

**Comment by KPanicEKS** [comment] 2015-05-20 23:11
Since downgrading could cause issues I think the only logical answer is to
keep the coyote backpack the same size (24 slots) and make the czech
backback 26 slots.

**Comment by R4Z0R49** [comment] 2015-05-21 00:15
Id like to scrap all the bags and have new ones created.

**Comment by R4Z0R49** [comment] 2015-05-21 00:20
There is a backpack mod on armaholic is someone wonts to track the owner down.

**Comment by CoftSock** [comment] 2015-05-21 03:59
The models have been release by BIS so you can easily change their shapes and add more visual pockets etc, the only thing i have problems with getting them to look decent with textures

**Comment by Quackster** [comment] 2015-05-26 02:25
What backpack mod were you looking at? I'll see if I can chase the owner.

**Comment by CoftSock** [comment] 2015-05-26 04:21
this one maybe? http://www.armaholic.com/page.php?id=13793

**Closed as completed** 2017-04-10 07:43 UTC
