### ISSUE TITLE
dd9b5b9 - Weapon Overhaul Issues.

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#435] opened 2015-05-10 19:55 UTC
Just a few things I noticed:
Had to relog after adding first attachment to weapon to be able to ads
Kobra - when unattached scope placed on ground model is corrupted (like wire fences, but much smaller)
Mosin - no scope can be fitted - intended?
m4a1 cco - inventory image does not show cco attached (forgot to check holo...doh)

**Comment by R4Z0R49** [comment] 2015-05-10 19:56
yea images are still wip.

**Comment by AsFoxy** [comment] 2015-05-10 22:19
"Had to relog after adding first attachment to weapon to be able to ads"
I never noticed any issues with this, if you can find a way to reproduce or if it's tied to a specific weapon then i can look into it.

Which scope did you try to attach to the mosin? The only one attachable to it is the Scoped sight attachment or something along those lines.

Some of the models have issues with shadows i'm aware of this but haven't had time to figure it out yet.

A lot of the inventory images haven't been made yet.

**Comment by Detoeni** [comment] 2015-05-11 06:24
Relog issue was effecting all weapons tried.
Scoped sight threw an error - can get on to server to repro, steam has wrong build and the link to files r4zor49 posted at musty has gone walkabouts....

**Comment by R4Z0R49** [comment] 2015-05-11 07:31
D, any chance you can get a video of whats happening ?

**Comment by Detoeni** [comment] 2015-05-11 07:34
I can try for a video but it might have to wait to I'm home - fraps does not play well on me works pc.

**Comment by R4Z0R49** [comment] 2015-05-11 08:06
Mosin
http://www.youtube.com/watch?v=C1A-r5c2gs4
Ak74
http://www.youtube.com/watch?v=XnmX3QvfhvI

Seems to be working ok on this side.

**Comment by Detoeni** [comment] 2015-05-11 12:53
not sure why I had a problem with mosin, worked fine for me today.
logging issue - not sure what I was doing yesterday to get this - might be an issue with my home pc only so i'll check again latter. Had something similar today, if I had a tin can in my inventory but no melee in slot 3 or pistol in slot 2, when I picked up the weapon it would put me into throw mode (for the can). Hitting "f" moved me to the primary weapon and it worked fine from that point onwards.
Yesterday when seeing this I was fresh spawn with no gear, but may have been getting something similar. I'll play some more latter and report back.

**Comment by R4Z0R49** [comment] 2015-05-11 16:36
Yea, the system will change your active weapon to what ever you have so when our script swaps the weapon your player char does not do any animation so it smooth just means you have to change weapon back after.

**Comment by Detoeni** [comment] 2015-05-11 18:11
- [ ]  when you add a kobra to akm you get an error message - 
  cannot open object
  dayz2work\assets\weapons\attachments\kobra\kobra.p3d
- [ ]  scope cannot be removed from crossbow - there is an option but when used text is shown in middle of screen "cannot remove" or something like that..
- [ ]  cco and scope on cross bow, lens renders badly (cco less so - scope shown) - all settings high - no post - gtx970
  I also get very bad frame when panning around while looking through scope - issue not seen with rifles or cross bow cco
  ![2015-05-11_00001](https://cloud.githubusercontent.com/assets/8584071/7571739/8235c6b4-f811-11e4-8162-10595047407c.jpg)

**Comment by AsFoxy** [comment] 2015-05-12 08:46
AKM Kobra has already been fixed internally.
I fixed crossbow attachments. a8a587b

Crossbow optic issues have always been there i think, i'll fix them at some point before 1.8.6.

**Comment by Detoeni** [comment] 2015-05-12 11:30
First time I've looked at one so I have not seen it before. Not sure whats causing the black flakes but it sort of looks like wrong blend function for the type of alpha used (I know nothing about arma render, but have spent too long messing in other engines). Also looks like the refection map is tiled over the lens rather than be clamped at a single pass (which would explain the shocking frame rate...)

**Comment by Detoeni** [comment] 2015-05-12 12:42
G17 -hitting "f" does not show that you have SD ammo loaded (are the SD pistol rounds going to added to the mod for this weapon?)
Pistol flash light has green equipment bag rather than model
Corruption issue on m24 clips (sorry for bad screen shot- even with gamma ramped up its hard to see)
![2015-05-12_00002](https://cloud.githubusercontent.com/assets/8584071/7587253/cb265c6c-f8ac-11e4-9236-01181c55947f.jpg)

**Comment by AsFoxy** [comment] 2015-05-12 13:24
M24 magazine model hasn't been changed and the shadow issue has always been there. We don't have access to the unbinarized version of that model to change it, though we could always make a new one.

Models for some of the items haven't been done yet, just like the icons.

SD mags for the G17 have been added to the game but probably not loot spawns yet. You can combine M9SD mags to G17SD though. You're right about it not showing SD when using SD mags though.

**Comment by KPanicEKS** [comment] 2015-05-14 20:49
just throwing this out there.

Is there any way we can include a 30 sec animation when switching scopes or
adding attachments to weapons. Right now it happens instantly and this
could really be taken advantage of-- Think about switching an M14 to DMR.
It will be too OP if you can switch between them in an instance. Currently
you have to swap them out in your bags and reload which takes some time and
valuable space in your inventory. I think adding a 30 or 60 sec animation
to attach a scope would be reasonable.

**Closed as completed** 2017-01-30 04:23 UTC
Labels: type:bug, status:wantfix
