### ISSUE TITLE
Mission Generator Problem 

### ISSUE THREAD

**Issue by fazmond** [DayZMod/DayZ#12] opened 2013-06-13 00:42 UTC
When using the Mission Generator with the options Anti teleport enabled and water mark on it causes people connecting to my server to get the constant loading screen bug , when using the older mission file from 1.7.6 the server loads up fine in the new 1.7.7 patch so there must be an issue somewhere with the generator

**Comment by R4Z0R49** [comment] 2013-06-13 09:07
This should now bee corrected.

**Comment by fazmond** [comment] 2013-06-13 15:00
Nope the newly generated mission causes and error when the mission is being read 
"Include file z\addons\dayz_code\system\REsec. not found"
then the server shuts down

**Comment by facoptere** [comment] 2013-06-13 15:06
This include is not found because you are not using 1.7.7 files.

**Comment by fazmond** [comment] 2013-06-13 15:08
well I am I downloaded the SERVER full install
maybe that needs checking it has all the correct bits in it
and I would of thought that it should be inside the mission file ?

**Comment by icomrade** [comment] 2013-06-13 16:18
Please try overwriting you server's @DayZmod install with the 1.7.7 Client Full version, or retry with the Server Full. I can't reproduce the error.

**Comment by fazmond** [comment] 2013-06-13 16:36
Nope that didnt work 
im thinking its still to do with the mission generator as before the last update it WOULD at least read the mission
I could send you my mission.pbo if you need take a look at it

**Comment by facoptere** [comment] 2013-06-13 16:40
could you send me your mission pbo?

**Comment by facoptere** [comment] 2013-06-13 18:27
it did not work

2013/6/13 fazmond notifications@github.com

**Comment by dayz-herbert** [comment] 2013-06-16 17:01
This issue was not fixed by the update as it would generate the file incomplete.
To fix this issue unpack the file and within this file:
dayz_[instanceID].Chernarus\init.sqf

Go to the last line and replace:
#include "\z\addons\dayz_code\system\REse
with:
#include "\z\addons\dayz_code\system\REsec.sqf"

This issue only occurs when you generate the mission file with AntiTP turned on.

**Comment by R4Z0R49** [comment] 2013-06-16 17:10
Its been passed onto the guy doing that site its not in our control.

**Comment by Silentspy** [comment] 2013-06-16 22:17
Generating a mission on the site now should work fine, appearently fopen had a buffer limit on some files..

**Closed as completed** 2013-06-17 03:55 UTC
Labels: type:bug

**Comment by fazmond** [comment] 2013-06-18 17:35
see I told ya :)
