### ISSUE TITLE
[Request] Ingame survival time in journal

### ISSUE THREAD

**Issue by rvett** [DayZMod/DayZ#679] opened 2016-05-10 21:21 UTC
This has been suggested already at the official forums at https://forums.dayz.com/topic/231612-journal-character-age-instead-of-zed-count/ , but since the devs still don't seem to have proper access, I thought it made sense to open a github issue for this.

The journal currently shows the "real time" (including offline time) the current character has survived for. A lot more interesting is the "ingame time" (excluding breaks), though. I think it would be great to have it shown in the journal as well. Might make a good motivation for people to try to survive as long as possible.

**Comment by ebayShopper** [comment] 2016-05-10 22:25
Duplicate of https://github.com/DayZMod/DayZ/issues/511

**Closed as completed by ebayShopper** 2016-05-10 22:25 UTC
